CREATE TABLE SERVICOS_CONTRATADOS(
	id_servicos_contratados int IDENTITY(1,1) PRIMARY KEY,
	id_servico int NOT NULL,
	cpf_usuario nvarchar(450) NOT NULL,
	dt_contratacao date NOT NULL default (getdate())
)

ALTER TABLE SERVICOS_CONTRATADOS ADD CONSTRAINT FK_SERVICOS_CONTRATADOS_X_SERVICO FOREIGN KEY (id_servico) REFERENCES
SERVICOS (id);

ALTER TABLE SERVICOS_CONTRATADOS ADD CONSTRAINT FK_SERVICOS_CONTRATADOS_X_USUARIOS FOREIGN KEY (cpf_usuario) REFERENCES
USUARIOS (cpf);