USE [ESCOLA_NC]
GO
SET NOCOUNT ON 
GO

CREATE OR ALTER PROCEDURE [dbo].[REL_SERVICOS_CONTRATADOS]
AS
BEGIN
	SELECT 
		SC.ID_SERVICO, 
		S.DESCRICAO, 
		COUNT(*) AS ASSINANTES,
		S.PRECO AS VALOR,
		(COUNT(*) * S.PRECO) AS FATURAMENTO 
	FROM SERVICOS_CONTRATADOS SC
		JOIN USUARIOS U 
			ON SC.CPF_USUARIO = U.CPF
		JOIN SERVICOS S 
			ON SC.ID_SERVICO = S.ID
	GROUP BY 
		SC.ID_SERVICO, 
		S.DESCRICAO,
		S.PRECO
	
	SET NOCOUNT OFF
END